site_name: D&D Session Logs
repo_url: https://github.com/gmr/dnd_session_logs
repo_name: gmr/dnd_session_logs
edit_uri: edit/main/site_src
docs_dir: site_src
site_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/5e-phb-background-imitation.png
  favicon: images/5e-phb-background-imitation.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true 