site_name: D&D Session Logs
site_description: Logs and recaps for all D&D campaign groups
site_author: Your Name
site_url: https://bytebard97.github.io/dnd_session_logs/

# Use Material for MkDocs theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips

extra_css:
  - custom_dd_style.css
  - 'https://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic'
  - 'https://fonts.googleapis.com/css?family=Libre+Baskerville:700'

extra_javascript:
  - js/statblock5e-inlined.html

# Source and output directories
# (site_src contains markdown, docs is the output for GitHub Pages)
docs_dir: site_src
site_dir: docs

# Plugins
plugins:
  - search
  - glightbox
  - include-markdown

# Basic markdown extensions for tabs and callouts
markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

# Directory URLs for GitHub Pages
use_directory_urls: false

# Manual navigation structure - this creates collapsible sections
nav:
  - Home: index.md
  - Monday:
    - Overview: monday/index.md
    - Campaign Overview: monday/campaign_overview.md
    - Players: monday/players/pcs.md
    - Factions:
      - Overview: monday/factions/index.md
      - House Glutthraz: monday/factions/house_glutthraz.md
      - House Cull'thaine: monday/factions/house_cullthaine.md
      - House Vaerixas: monday/factions/house_vaerixas.md
    - NPCs:
      - Overview: monday/npcs/index.md
      - House Talzar:
        - Matron Severine: monday/npcs/matron_severine.md
        - Valandor T'alzar: monday/npcs/valandor_talzar.md
        - Vyssinia Talzar: monday/npcs/vyssinia_talzar.md
        - Lirael T'alzar: monday/npcs/lirael_talzar.md
        - Miraleth T'alzar: monday/npcs/miraleth_talzar.md
      - House Staff:
        - Prefect Kaelen: monday/npcs/prefect_kaelen.md
        - Grumble: monday/npcs/grumble.md
        - Splurg: monday/npcs/splurg.md
        - Veridia: monday/npcs/veridia.md
        - Bronzidon ("Nugget"): monday/npcs/bronzidon.md
      - House Glutthraz:
        - Matron Zephyra: monday/npcs/matron_zephyra.md
      - Ferry Crew:
        - Borok the Silent: monday/npcs/borok_the_silent.md
        - Fadda Brinebless: monday/npcs/fadda_brinebless.md
        - Black Loch Keelhauler: monday/npcs/black_loch_keelhauler.md
    - Locations:
      - Overview: monday/locations/index.md
      - Major Regions:
        - Black Loch Codex: monday/locations/black_loch_codex.md
        - Vlyn'darastyl: monday/locations/vlyn_darastyl.md
        - The Black Loch Region: monday/locations/black_loch_region.md
        - Cinderfork Foundry: monday/locations/cinderfork_foundry.md
      - Key Locations:
        - T'alzar Tower: monday/locations/talzar_tower.md
        - Valandor's Workshop: monday/locations/valandor_workshop.md
        - Night-Tide Docks: monday/locations/night_tide_docks.md
        - The Black Loch: monday/locations/black_loch.md
        - Lost Catacombs of Auldbaern: monday/locations/lost_catacombs_auldbaern.md
    - Lore:
      - Overview: monday/lore/index.md
      - Drow Pantheon: monday/lore/drow_pantheon.md
      - Drow Society: monday/lore/drow_society.md
    - Items:
      - Overview: monday/items/index.md
      - T'alzarine Prime Explosives: monday/items/talzarine_prime_explosives.md
    - Credits: monday/credits.md
    - Session Archives:
      - Recaps:
        - Overview: monday/recaps/index.md
        - Session 6: monday/recaps/recap_session_6.md
        - Session 5: monday/recaps/recap_session_5.md
        - Session 4: monday/recaps/recap_session_4.md
        - Session 3: monday/recaps/recap_session_3.md
        - Session 2: monday/recaps/recap_session_2.md
        - Session 1: monday/recaps/recap_session_1.md
      - Quest Logs:
        - Overview: monday/logs/index.md
        - Session 6: monday/logs/log_session_6.md
        - Session 5: monday/logs/log_session_5.md
        - Session 4: monday/logs/log_session_4.md
        - Session 3: monday/logs/log_session_3.md
        - Session 2: monday/logs/log_session_2.md
        - Session 1: monday/logs/log_session_1.md
  - Wednesday:
    - Overview: wednesday/index.md
  - Friday:
    - Overview: friday/index.md 